name: pull-req-preview

on:
  pull_request:
    branches:
      - staging

jobs:
  pull-req-preview:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: ./build.sh pull-req-preview

      - name: checkout branch for publish
        run: git checkout -b pull-req-preview-public

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" | exit 0
      - name: push
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" --follow-tags -f | exit 0
